name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      
      - run: pnpm install --no-frozen-lockfile
      
      # On utilise la commande de build que ton projet connaît
      - run: pnpm build 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # On déploie TOUT le projet. 
          # Si l'index.html est dans un sous-dossier, on le saura tout de suite.
          folder: . 
          branch: gh-pages
