name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          
      # 1. On installe tout proprement
      - run: pnpm install --no-frozen-lockfile
      
      # 2. On lance la construction
      - run: pnpm build 

      # 3. ON DÉPLOIE LE BON DOSSIER
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/web/dist # C'est ici que se cache ton index.html !
          branch: gh-pages


